# Generated by Django 5.0.1 on 2024-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
