# Generated by Django 5.0.1 on 2024-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
