# Generated by Django 5.0.1 on 2024-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cartitem_price'),
        ('order', '0002_remove_specialoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='category',
            field=models.ManyToManyField(to='menu.category'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
